# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RJt3wBT86RUuCQK1NrcYtPIgJzP0Ia4EnaSiE6TaDYR9wLhQVxzKJ6ZIorgEFYPgClaS6+YLzITel4d0qdvbvxKGty5Znni5hYN187s7h06bcVDD5ZfovPBSGrGcJ/vc2kvd/AaeKsbp2+VhqYE8B+QDE5zf75/xylNu10B17Asi5YplHmD6FzaOqoj4IslUkJVTrjU3Gu3oN3iMOqaaqyubdiv1ow6vKG9vdg/2XHqsoFFseiWcBhoTGpMtEqe6LLS4Cl5DvDxwCaLsQ83FifkT4yK/SLzvWwbfGcyg6DmApIlYC/5Hd3eeom23e/JqIjbZ5n3YogZPI2vdfQimTEzOhAIqrxagKFQqfXzh8yelHZFtMPAZBfAwddknxo9UCOpgBk3K3l2ui3ywCd8wng8kwI//kaCnhpADOyn9sIpxUTEWZ69/aYja9hM1GKusmEumGeEcWsv80hndvWFT3BsWqm43ak5f/OlCjTWzGlHjm2tl/3WOxXArBIszTpNt+afn7w6dwqE2eRB62XlMQH4AJX8HZDO+yB6hWnot52jdpQWdg1PmZ/BiFlAVbyCsuNW1X5qyAw6P3rjgQTzzbSbXKsaeKJxlPBOUcRqEB0cnWC29AmMuE8meBEL6xJ/hqzaO6+u618KTOHLRm9dBrOtWHadb892aYNp3NcOUr50="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
