travis:
  secure:
    BINSTAR_TOKEN: RQB9COc+FpnENDX6pf9OcLshzlZwY9Ss90zk0DWyY9ap/exfgr3jllllN6dS41DtXlT/J4A9lb+csb+6q59RA64AyKcG3yfm0v0O1CcZKUv3gl3KcMqB/mcpIVXpt55cUHD2Kg8b3fmK7I1ZJMCIi3auu24V9Dnwo9fNsnEGmL7cYoYEF0e+vLqbEQEpDVP8lOOVI2c/q8BYVJ9UVyDTGKZkXxjdilBoLk6bK3sXCJRrXdKhO0a9wOiy/iDz65j2gXDQ7QN7xiQFxho/EEQM0Avp/37YnvjzOz2ZGrm03Iy8c8X1L79CxAybkQmn2fv+aUJwgX7E963bsZOIO0PELooSVMynlaU1dUCXBO5Fn41UAYw0PbF9FhsK16gT83f7ZWYhFyOoiBK7V4mCV8CNHqXl5djOwks8mc7Brkrh9hAH+Lm0CKHqPYdWJsjX2P/kCv/WYMv69iSk7w+oZVrlr/MLm2tj2YG4vOOtqvlUSxv1sUhnmvvI1xnaUPQ9gKh6+D6TOsN3vBa5P7HP2yHx6OxvpvwUD35o4qXajtUwWPLwxAlBXmw4uMfh53efa4SYGVdCuoXVOvN/GktFhCDsLNrF6gAvi0VcyijwdSK55pHtSTOKze5kFpBPDnlMgbVeYnUYVf6C2zfa9noXhjW07CyVTxSXpl83rKclSUWVJAE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
