travis:
  secure:
    BINSTAR_TOKEN: Q43LZ9XbB8/5rw1a9X7CKs7tTEuBSg7i2N5q98Zg7fuvYFiGt+ldVAmdzoCtz+7cR671gvZfXxlKdQxbgq5hDS9XlVvQgsAyzIFDzN4FMCJMe30ENP0QWhqh9Ns0L/OTbqqQpvXRfX75gYvGOjz07DREGak4hU1STJmrjr8k8ZQsyfRYfZQHxUThAnRFEut55I5n5CFttE94O4x9j8rXCcqnuxQw4GKZGS/qoe0dDe83doCcqq21LMRgSdVznbAWOldPErQ3+F0SbbH5IzzWg/UaZ68R1XNXPdWza/yFoUg/ZCxDWVP47KG7tm5GprsFcTr+fsTSnONgUhuxlACo2LZDhIVPn1NqJuHBjEvuMMIS8heuG2EKd116xAl3Rtzyfs7BVDwIMI12nSvexdk3dxCvU/qFcrDgCEHfF2ViFpbQwwkEc82I5Tiyr5cE/itK6QJC+Bajrs5PMBNebT0QaG0/PAfymHfI+ka/0Iq69TAEFyPe91KBI+7Itk0k+2AQGAFIoupCW0JiKI3mX9A5/yPvRiGHq4iyt1BM55m5LMUWiOFlB3BcCmGUE9mYfQIcAzxxa+hgNvHO9CRP2YIapPATZVIbUnEBunMjPXqyQhEM23rg1c/Uur1ZuOqlj6CPbWtGOZVapSbp5NcnsAxtVisOtMq7o/4f8CCpH4WixT0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
