travis:
  secure:
    BINSTAR_TOKEN: RJt3wBT86RUuCQK1NrcYtPIgJzP0Ia4EnaSiE6TaDYR9wLhQVxzKJ6ZIorgEFYPgClaS6+YLzITel4d0qdvbvxKGty5Znni5hYN187s7h06bcVDD5ZfovPBSGrGcJ/vc2kvd/AaeKsbp2+VhqYE8B+QDE5zf75/xylNu10B17Asi5YplHmD6FzaOqoj4IslUkJVTrjU3Gu3oN3iMOqaaqyubdiv1ow6vKG9vdg/2XHqsoFFseiWcBhoTGpMtEqe6LLS4Cl5DvDxwCaLsQ83FifkT4yK/SLzvWwbfGcyg6DmApIlYC/5Hd3eeom23e/JqIjbZ5n3YogZPI2vdfQimTEzOhAIqrxagKFQqfXzh8yelHZFtMPAZBfAwddknxo9UCOpgBk3K3l2ui3ywCd8wng8kwI//kaCnhpADOyn9sIpxUTEWZ69/aYja9hM1GKusmEumGeEcWsv80hndvWFT3BsWqm43ak5f/OlCjTWzGlHjm2tl/3WOxXArBIszTpNt+afn7w6dwqE2eRB62XlMQH4AJX8HZDO+yB6hWnot52jdpQWdg1PmZ/BiFlAVbyCsuNW1X5qyAw6P3rjgQTzzbSbXKsaeKJxlPBOUcRqEB0cnWC29AmMuE8meBEL6xJ/hqzaO6+u618KTOHLRm9dBrOtWHadb892aYNp3NcOUr50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
